import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const backgroundResearchJobs = sqliteTable("background_research_jobs", {
  id: text("id").primaryKey(),
  campaignId: text("campaign_id").notNull(),
  campaignName: text("campaign_name").notNull(),
  topic: text("topic").notNull(),
  emailTemplate: text("email_template").notNull(),
  brief: text("brief"),
  createdBy: text("created_by").notNull(),
  status: text("status").notNull().default("queued"),
  totalItems: integer("total_items").notNull().default(0),
  completedItems: integer("completed_items").notNull().default(0),
  successfulItems: integer("successful_items").notNull().default(0),
  failedItems: integer("failed_items").notNull().default(0),
  draftsCreated: integer("drafts_created").notNull().default(0),
  contactsFound: integer("contacts_found").notNull().default(0),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull(),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("background_research_jobs_status_idx").on(table.status),
  index("background_research_jobs_campaign_idx").on(table.campaignId),
]);

export const backgroundResearchItems = sqliteTable("background_research_items", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull(),
  inputType: text("input_type").notNull(),
  inputValue: text("input_value").notNull(),
  payload: text("payload").notNull(),
  status: text("status").notNull().default("queued"),
  attempts: integer("attempts").notNull().default(0),
  claimedBy: text("claimed_by"),
  result: text("result"),
  error: text("error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("background_research_items_job_input_uidx").on(table.jobId, table.inputType, table.inputValue),
  index("background_research_items_job_status_idx").on(table.jobId, table.status),
]);

export const emailAnalyticsEvents = sqliteTable("email_analytics_events", {
  id: text("id").primaryKey(),
  providerEventKey: text("provider_event_key").notNull(),
  campaignId: text("campaign_id"),
  generatedEmailId: text("generated_email_id"),
  emailSendId: text("email_send_id"),
  messageId: text("message_id"),
  recipientEmail: text("recipient_email").notNull(),
  senderEmail: text("sender_email"),
  subject: text("subject"),
  event: text("event").notNull(),
  eventAt: text("event_at").notNull(),
  ipAddress: text("ip_address"),
  link: text("link"),
  reason: text("reason"),
  tag: text("tag"),
  payload: text("payload").notNull(),
  createdAt: text("created_at").notNull(),
}, (table) => [
  uniqueIndex("email_analytics_events_provider_uidx").on(table.providerEventKey),
  index("email_analytics_events_campaign_idx").on(table.campaignId),
  index("email_analytics_events_recipient_idx").on(table.recipientEmail),
  index("email_analytics_events_date_idx").on(table.eventAt),
  index("email_analytics_events_message_idx").on(table.messageId),
]);
