import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const backgroundResearchJobs = sqliteTable("background_research_jobs", {
  id: text("id").primaryKey(),
  campaignId: text("campaign_id").notNull(),
  campaignName: text("campaign_name").notNull(),
  topic: text("topic").notNull(),
  emailTemplate: text("email_template").notNull(),
  brief: text("brief"),
  createdBy: text("created_by").notNull(),
  status: text("status").notNull().default("queued"),
  totalItems: integer("total_items").notNull().default(0),
  completedItems: integer("completed_items").notNull().default(0),
  successfulItems: integer("successful_items").notNull().default(0),
  failedItems: integer("failed_items").notNull().default(0),
  draftsCreated: integer("drafts_created").notNull().default(0),
  contactsFound: integer("contacts_found").notNull().default(0),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull(),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("background_research_jobs_status_idx").on(table.status),
  index("background_research_jobs_campaign_idx").on(table.campaignId),
]);

export const backgroundResearchItems = sqliteTable("background_research_items", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull(),
  inputType: text("input_type").notNull(),
  inputValue: text("input_value").notNull(),
  payload: text("payload").notNull(),
  status: text("status").notNull().default("queued"),
  attempts: integer("attempts").notNull().default(0),
  claimedBy: text("claimed_by"),
  result: text("result"),
  error: text("error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("background_research_items_job_input_uidx").on(table.jobId, table.inputType, table.inputValue),
  index("background_research_items_job_status_idx").on(table.jobId, table.status),
]);

export const emailAnalyticsEvents = sqliteTable("email_analytics_events", {
  id: text("id").primaryKey(),
  providerEventKey: text("provider_event_key").notNull(),
  campaignId: text("campaign_id"),
  generatedEmailId: text("generated_email_id"),
  emailSendId: text("email_send_id"),
  messageId: text("message_id"),
  recipientEmail: text("recipient_email").notNull(),
  senderEmail: text("sender_email"),
  subject: text("subject"),
  event: text("event").notNull(),
  eventAt: text("event_at").notNull(),
  ipAddress: text("ip_address"),
  link: text("link"),
  reason: text("reason"),
  tag: text("tag"),
  payload: text("payload").notNull(),
  createdAt: text("created_at").notNull(),
}, (table) => [
  uniqueIndex("email_analytics_events_provider_uidx").on(table.providerEventKey),
  index("email_analytics_events_campaign_idx").on(table.campaignId),
  index("email_analytics_events_recipient_idx").on(table.recipientEmail),
  index("email_analytics_events_date_idx").on(table.eventAt),
  index("email_analytics_events_message_idx").on(table.messageId),
]);

export const emailValidationJobs = sqliteTable("email_validation_jobs", {
  id: text("id").primaryKey(),
  status: text("status").notNull().default("queued"),
  scheduledFor: text("scheduled_for"),
  totalItems: integer("total_items").notNull().default(0),
  processedItems: integer("processed_items").notNull().default(0),
  validItems: integer("valid_items").notNull().default(0),
  riskyItems: integer("risky_items").notNull().default(0),
  invalidItems: integer("invalid_items").notNull().default(0),
  unknownItems: integer("unknown_items").notNull().default(0),
  failedItems: integer("failed_items").notNull().default(0),
  createdBy: text("created_by").notNull(),
  lastError: text("last_error"),
  cancelRequested: integer("cancel_requested").notNull().default(0),
  createdAt: text("created_at").notNull(),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("email_validation_jobs_status_idx").on(table.status),
  index("email_validation_jobs_schedule_idx").on(table.scheduledFor),
]);

export const emailValidationItems = sqliteTable("email_validation_items", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull(),
  contactId: text("contact_id").notNull(),
  email: text("email").notNull(),
  status: text("status").notNull().default("queued"),
  verdict: text("verdict"),
  score: integer("score"),
  attempts: integer("attempts").notNull().default(0),
  error: text("error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("email_validation_items_job_contact_uidx").on(table.jobId, table.contactId),
  index("email_validation_items_job_status_idx").on(table.jobId, table.status),
  index("email_validation_items_email_idx").on(table.email),
]);

export const emailValidationResults = sqliteTable("email_validation_results", {
  contactId: text("contact_id").primaryKey(),
  email: text("email").notNull(),
  normalizedEmail: text("normalized_email").notNull(),
  domain: text("domain").notNull(),
  verdict: text("verdict").notNull(),
  score: integer("score").notNull(),
  syntaxValid: integer("syntax_valid").notNull(),
  domainReachable: integer("domain_reachable"),
  roleBased: integer("role_based").notNull().default(0),
  disposable: integer("disposable").notNull().default(0),
  previousHardBounce: integer("previous_hard_bounce").notNull().default(0),
  previousSoftBounce: integer("previous_soft_bounce").notNull().default(0),
  previousDelivered: integer("previous_delivered").notNull().default(0),
  complaint: integer("complaint").notNull().default(0),
  unsubscribed: integer("unsubscribed").notNull().default(0),
  reasons: text("reasons").notNull(),
  mxRecords: text("mx_records").notNull(),
  jobId: text("job_id").notNull(),
  validatedAt: text("validated_at").notNull(),
}, (table) => [
  index("email_validation_results_email_idx").on(table.normalizedEmail),
  index("email_validation_results_verdict_idx").on(table.verdict),
]);

export const emailDomainValidationCache = sqliteTable("email_domain_validation_cache", {
  domain: text("domain").primaryKey(),
  reachable: integer("reachable"),
  mxRecords: text("mx_records").notNull(),
  fallbackAddressRecord: integer("fallback_address_record").notNull().default(0),
  error: text("error"),
  checkedAt: text("checked_at").notNull(),
});
